### ISSUE TITLE
keep committing your work

### ISSUE THREAD

**Issue by tkimva** [tkimva/statistical-modeling-and-analysis#9]
@ericzy89  Yue,

As of now, your recent update was 2 days ago. You should keep committing your daily work in here

![screenshot](https://cloud.githubusercontent.com/assets/993376/6831615/ab470200-d2de-11e4-8d41-177f64337039.png)
![screenshot](https://cloud.githubusercontent.com/assets/993376/6831616/ae289146-d2de-11e4-9b6b-9e1aeeeedc92.png)

**Comment by ericzy89** [comment]
@tkimva Taeyoung,

My schedule is spend two  days on paper reading part, so I usually don`t have anything solid for one or two days. I am working on the programming part right now. David set the first checkpoint of my assignment on Thursday so I will upload the slides by tomorrow.

**Comment by tkimva** [comment]
@ericzy89 
If you did paper reading, please upload your summary of reading. Upload what you read and how you think how you understood, what you learned. This is work not your hobby reading. The committed stuff should not be solid and it should be used your workplace. That's how you can show your progress. Log your work, which can be trackable, otherwise, it will be unproductive. Please focus on your programming part now.
